name: Scala CI

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: adopt:11
          apps: sbtn bloop
      - name: Build js
        run: ./build.sh
      - name: copy artifacts
        run: |
          mkdir public
          cp index.html rps.js public/
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
